/**
 * Permission catalogue. Deny-by-default: any permission not explicitly
 * listed for a role in ROLE_PERMISSIONS is denied. See docs/RBAC.md.
 */
export const PERMISSIONS = {
  PROPERTIES_VIEW_PUBLIC: "properties:view_public",
  PROPERTIES_MANAGE_ALL: "properties:manage_all",
  PROPERTIES_MANAGE_OWN: "properties:manage_own",
  PARTNERS_VIEW_APPLICATIONS: "partners:view_applications",
  PARTNERS_APPROVE_REJECT: "partners:approve_reject",
  PARTNERS_SUSPEND: "partners:suspend",
  COMPLIANCE_VERIFY_DOCUMENTS: "compliance:verify_documents",
  CLIENTS_VIEW_OWN: "clients:view_own",
  LEADS_MANAGE_OWN: "leads:manage_own",
  LEADS_ASSIGN: "leads:assign",
  AUDIT_VIEW: "audit:view",
  SYSTEM_MANAGE_SETTINGS: "system:manage_settings",
  COMMISSIONS_VIEW: "commissions:view",
  // Phase 2
  DEVELOPER_MANAGE_OWN: "developer:manage_own",
  DEALS_MANAGE_OWN: "deals:manage_own",
  DEALS_MANAGE_ALL: "deals:manage_all",
  COMMISSIONS_MANAGE: "commissions:manage",
  LEADS_MARKETPLACE_VIEW: "leads:marketplace_view",
  LEADS_MARKETPLACE_ACCEPT: "leads:marketplace_accept",
  MARKETING_MANAGE: "marketing:manage",
  ANALYTICS_VIEW: "analytics:view",
  // Phase 3: DLD Independent Brokerage Network
  NETWORK_CONNECT: "network:connect",
  NETWORK_MESSAGE: "network:message",
  REFERRALS_MANAGE_OWN: "referrals:manage_own",
  DEALS_COLLABORATE: "deals:collaborate",
  COMMISSION_SPLITS_VIEW_OWN: "commission_splits:view_own",
  LISTINGS_SHARE_OWN: "listings:share_own",
  REVIEWS_SUBMIT: "reviews:submit",
  NETWORK_MANAGE_ALL: "network:manage_all",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type AppRole =
  | "SUPER_ADMIN"
  | "ADMINISTRATOR"
  | "COMPLIANCE_MANAGER"
  | "SALES_MANAGER"
  | "PARTNER_MANAGER"
  | "BROKER"
  | "PARTNER_COMPANY"
  | "PROPERTY_OWNER"
  | "DEVELOPER"
  | "BUYER"
  | "TENANT"
  | "INVESTOR"
  | "MARKETING_MANAGER"
  | "FINANCE_MANAGER"
  | "SUPPORT_AGENT";

const {
  PROPERTIES_VIEW_PUBLIC,
  PROPERTIES_MANAGE_ALL,
  PROPERTIES_MANAGE_OWN,
  PARTNERS_VIEW_APPLICATIONS,
  PARTNERS_APPROVE_REJECT,
  PARTNERS_SUSPEND,
  COMPLIANCE_VERIFY_DOCUMENTS,
  CLIENTS_VIEW_OWN,
  LEADS_MANAGE_OWN,
  LEADS_ASSIGN,
  AUDIT_VIEW,
  SYSTEM_MANAGE_SETTINGS,
  COMMISSIONS_VIEW,
  DEVELOPER_MANAGE_OWN,
  DEALS_MANAGE_OWN,
  DEALS_MANAGE_ALL,
  COMMISSIONS_MANAGE,
  LEADS_MARKETPLACE_VIEW,
  LEADS_MARKETPLACE_ACCEPT,
  MARKETING_MANAGE,
  ANALYTICS_VIEW,
  NETWORK_CONNECT,
  NETWORK_MESSAGE,
  REFERRALS_MANAGE_OWN,
  DEALS_COLLABORATE,
  COMMISSION_SPLITS_VIEW_OWN,
  LISTINGS_SHARE_OWN,
  REVIEWS_SUBMIT,
  NETWORK_MANAGE_ALL,
} = PERMISSIONS;

/** Explicit allow-list per role. Roles/permissions absent here are denied. */
export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  SUPER_ADMIN: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PROPERTIES_MANAGE_OWN,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    COMPLIANCE_VERIFY_DOCUMENTS,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    AUDIT_VIEW,
    SYSTEM_MANAGE_SETTINGS,
    COMMISSIONS_VIEW,
    DEVELOPER_MANAGE_OWN,
    DEALS_MANAGE_OWN,
    DEALS_MANAGE_ALL,
    COMMISSIONS_MANAGE,
    LEADS_MARKETPLACE_VIEW,
    LEADS_MARKETPLACE_ACCEPT,
    MARKETING_MANAGE,
    ANALYTICS_VIEW,
    NETWORK_CONNECT,
    NETWORK_MESSAGE,
    REFERRALS_MANAGE_OWN,
    DEALS_COLLABORATE,
    COMMISSION_SPLITS_VIEW_OWN,
    LISTINGS_SHARE_OWN,
    REVIEWS_SUBMIT,
    NETWORK_MANAGE_ALL,
  ],
  ADMINISTRATOR: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PROPERTIES_MANAGE_OWN,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    AUDIT_VIEW,
    SYSTEM_MANAGE_SETTINGS,
    COMMISSIONS_VIEW,
    DEALS_MANAGE_ALL,
    COMMISSIONS_MANAGE,
    LEADS_MARKETPLACE_VIEW,
    MARKETING_MANAGE,
    ANALYTICS_VIEW,
    NETWORK_MANAGE_ALL,
  ],
  COMPLIANCE_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    COMPLIANCE_VERIFY_DOCUMENTS,
    AUDIT_VIEW,
    NETWORK_MANAGE_ALL,
  ],
  SALES_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    DEALS_MANAGE_ALL,
    LEADS_MARKETPLACE_VIEW,
    ANALYTICS_VIEW,
  ],
  PARTNER_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    DEALS_MANAGE_ALL,
    LEADS_MARKETPLACE_VIEW,
    ANALYTICS_VIEW,
  ],
  BROKER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_OWN,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    COMMISSIONS_VIEW,
    DEALS_MANAGE_OWN,
    LEADS_MARKETPLACE_VIEW,
    LEADS_MARKETPLACE_ACCEPT,
    NETWORK_CONNECT,
    NETWORK_MESSAGE,
    REFERRALS_MANAGE_OWN,
    DEALS_COLLABORATE,
    COMMISSION_SPLITS_VIEW_OWN,
    LISTINGS_SHARE_OWN,
    REVIEWS_SUBMIT,
  ],
  PARTNER_COMPANY: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_OWN,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    COMMISSIONS_VIEW,
    DEALS_MANAGE_OWN,
    LEADS_MARKETPLACE_VIEW,
    LEADS_MARKETPLACE_ACCEPT,
    NETWORK_CONNECT,
    NETWORK_MESSAGE,
    REFERRALS_MANAGE_OWN,
    DEALS_COLLABORATE,
    COMMISSION_SPLITS_VIEW_OWN,
    LISTINGS_SHARE_OWN,
    REVIEWS_SUBMIT,
  ],
  PROPERTY_OWNER: [PROPERTIES_VIEW_PUBLIC],
  DEVELOPER: [PROPERTIES_VIEW_PUBLIC, DEVELOPER_MANAGE_OWN],
  BUYER: [PROPERTIES_VIEW_PUBLIC],
  TENANT: [PROPERTIES_VIEW_PUBLIC],
  INVESTOR: [PROPERTIES_VIEW_PUBLIC],
  MARKETING_MANAGER: [PROPERTIES_VIEW_PUBLIC, MARKETING_MANAGE, ANALYTICS_VIEW],
  FINANCE_MANAGER: [PROPERTIES_VIEW_PUBLIC, COMMISSIONS_VIEW, COMMISSIONS_MANAGE, ANALYTICS_VIEW],
  SUPPORT_AGENT: [PROPERTIES_VIEW_PUBLIC, CLIENTS_VIEW_OWN, LEADS_MANAGE_OWN],
};

export function roleHasPermission(role: AppRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function anyRoleHasPermission(roles: AppRole[], permission: Permission): boolean {
  return roles.some((role) => roleHasPermission(role, permission));
}
