/**
 * Permission catalogue. Deny-by-default: any permission not explicitly
 * listed for a role in ROLE_PERMISSIONS is denied. See docs/RBAC.md.
 */
export const PERMISSIONS = {
  PROPERTIES_VIEW_PUBLIC: "properties:view_public",
  PROPERTIES_MANAGE_ALL: "properties:manage_all",
  PROPERTIES_MANAGE_OWN: "properties:manage_own",
  PARTNERS_VIEW_APPLICATIONS: "partners:view_applications",
  PARTNERS_APPROVE_REJECT: "partners:approve_reject",
  PARTNERS_SUSPEND: "partners:suspend",
  COMPLIANCE_VERIFY_DOCUMENTS: "compliance:verify_documents",
  CLIENTS_VIEW_OWN: "clients:view_own",
  LEADS_MANAGE_OWN: "leads:manage_own",
  LEADS_ASSIGN: "leads:assign",
  AUDIT_VIEW: "audit:view",
  SYSTEM_MANAGE_SETTINGS: "system:manage_settings",
  COMMISSIONS_VIEW: "commissions:view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type AppRole =
  | "SUPER_ADMIN"
  | "ADMINISTRATOR"
  | "COMPLIANCE_MANAGER"
  | "SALES_MANAGER"
  | "PARTNER_MANAGER"
  | "BROKER"
  | "PARTNER_COMPANY"
  | "PROPERTY_OWNER"
  | "DEVELOPER"
  | "BUYER"
  | "TENANT"
  | "INVESTOR"
  | "MARKETING_MANAGER"
  | "FINANCE_MANAGER"
  | "SUPPORT_AGENT";

const {
  PROPERTIES_VIEW_PUBLIC,
  PROPERTIES_MANAGE_ALL,
  PROPERTIES_MANAGE_OWN,
  PARTNERS_VIEW_APPLICATIONS,
  PARTNERS_APPROVE_REJECT,
  PARTNERS_SUSPEND,
  COMPLIANCE_VERIFY_DOCUMENTS,
  CLIENTS_VIEW_OWN,
  LEADS_MANAGE_OWN,
  LEADS_ASSIGN,
  AUDIT_VIEW,
  SYSTEM_MANAGE_SETTINGS,
  COMMISSIONS_VIEW,
} = PERMISSIONS;

/** Explicit allow-list per role. Roles/permissions absent here are denied. */
export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  SUPER_ADMIN: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PROPERTIES_MANAGE_OWN,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    COMPLIANCE_VERIFY_DOCUMENTS,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    AUDIT_VIEW,
    SYSTEM_MANAGE_SETTINGS,
    COMMISSIONS_VIEW,
  ],
  ADMINISTRATOR: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PROPERTIES_MANAGE_OWN,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
    AUDIT_VIEW,
    SYSTEM_MANAGE_SETTINGS,
    COMMISSIONS_VIEW,
  ],
  COMPLIANCE_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    COMPLIANCE_VERIFY_DOCUMENTS,
    AUDIT_VIEW,
  ],
  SALES_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
  ],
  PARTNER_MANAGER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_ALL,
    PARTNERS_VIEW_APPLICATIONS,
    PARTNERS_APPROVE_REJECT,
    PARTNERS_SUSPEND,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    LEADS_ASSIGN,
  ],
  BROKER: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_OWN,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    COMMISSIONS_VIEW,
  ],
  PARTNER_COMPANY: [
    PROPERTIES_VIEW_PUBLIC,
    PROPERTIES_MANAGE_OWN,
    CLIENTS_VIEW_OWN,
    LEADS_MANAGE_OWN,
    COMMISSIONS_VIEW,
  ],
  PROPERTY_OWNER: [PROPERTIES_VIEW_PUBLIC],
  DEVELOPER: [PROPERTIES_VIEW_PUBLIC],
  BUYER: [PROPERTIES_VIEW_PUBLIC],
  TENANT: [PROPERTIES_VIEW_PUBLIC],
  INVESTOR: [PROPERTIES_VIEW_PUBLIC],
  MARKETING_MANAGER: [PROPERTIES_VIEW_PUBLIC],
  FINANCE_MANAGER: [PROPERTIES_VIEW_PUBLIC, COMMISSIONS_VIEW],
  SUPPORT_AGENT: [PROPERTIES_VIEW_PUBLIC, CLIENTS_VIEW_OWN, LEADS_MANAGE_OWN],
};

export function roleHasPermission(role: AppRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function anyRoleHasPermission(roles: AppRole[], permission: Permission): boolean {
  return roles.some((role) => roleHasPermission(role, permission));
}
